### ISSUE TITLE
Add a command line option to clear the configs

### ISSUE THREAD

**Issue by ayaka14732** [yixiaoer/tpux#2]
We should add a command line option to clear the changes of the config files

**Comment by yixiaoer** [comment]
Completed the functions to clear the configs. Next, I'll add the command line option.

**Comment by yixiaoer** [comment]
Completed the functions to clear the configs. Next, will add the command line option.

**Comment by yixiaoer** [comment]
Added command line option`--clear` (or `-c`) to clear the configs.
